/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.peacetrue.generator.plugin;

import org.gradle.api.Plugin;
import org.gradle.api.Project;

import java.util.HashMap;
import java.util.Map;

/** 生成器插件 */
public class GeneratorPlugin implements Plugin<Project> {

    @Override
    public void apply(Project project) {
        project.getTasks().register("peacetrueGenerate", GeneratorTask.class, task -> {
            //设置目标路径为当前项目
            Map<String, Object> properties = task.getClient().getProperties();
            if (properties == null) {
                properties = new HashMap<>();
                task.getClient().setProperties(properties);
            }
            properties.putIfAbsent("peacetrue.generator.target-path", task.getProject().getRootDir().getPath());
        });
    }

}
